config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'registrations' }
	root to: 'home#index'
	resources :buyers do 
		member do
			get :pending_buyer_comments
			post :update_pending_buyer_comments
			get :pending_buyer_approval
			post :update_pending_buyer_approval
			get :buyer_approved_items
			post :update_buyer_approved_items
		end
		resources :couriers do 
   		member do
   			get 'sample_type_items'
   			get 'approve_status'
   		end
   		resources :items do
   			collection do
	   			get 'delete_multiple_items'
	   			post 'save_items'
	   			get 'edit_delivery_items'
	   			post 'update_delivery_items'
				end
   		end
		end
		member do 
			get 'get_teams'
		end
		resources :teams do
			resources :team_members
		end
	end
	resources :users
	resources :sample_types
	get 'reports', to: 'reports#index'
	get 'download_report', to: 'reports#download_report'
	get 'send_reminder_mail', to: 'items#send_reminder_mail'
	get 'all_couriers', to: 'couriers#all_couriers'
	get 'new_courier', to: 'couriers#new_courier'
	post 'save_courier', to: 'couriers#save_courier'
	get 'undelivered_couriers', to: 'couriers#undelivered_couriers'
	post 'update_courier_delivery_dates', to: 'couriers#update_courier_delivery_dates'
	get 'pending_buyer_comments', to: 'items#pending_buyer_comments'
	get 'pending_buyer_approval', to: 'items#pending_buyer_approval'
	get 'buyer_approved_items', to: 'items#buyer_approved_items'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row mt-20">
	<div class="col-lg-4">
		<%= link_to all_couriers_path do %>	
			<div class="card custom-card shadow-sm card-style">
			  <div class="card-body">
			    <h5 class="card-title text-center">Total couriers sent</h5>
			    <h1 class="card-text text-center"><%= Courier.sent(current_user).count%></h1>
			  </div>
			</div>
		<% end %>
	</div>
	<div class="col-lg-4">
		<%= link_to undelivered_couriers_path do %>	
			<div class="card custom-card shadow-sm card-style">
			  <div class="card-body">
			    <h5 class="card-title text-center">In Transit</h5>
			    <h1 class="card-text text-center"><%= Courier.pending_delivery(current_user).count%></h1>
			  </div>
			</div>
		<% end %>
	</div>
	<div class="col-lg-4">
		<div class="card custom-card shadow-sm card-style">
		  <div class="card-body">
		    <h5 class="card-title text-center">Total couriers delivered</h5>
		    <h1 class="card-text text-center"><%= Courier.delivered(current_user).count%></h1>
		  </div>
		</div>
	</div>
</div>
<div class="row mt-20">
	<div class="col-lg-4">
		<div class="card custom-card shadow-sm card-style">
		  <div class="card-body">
		    <h5 class="card-title text-center">Total items sent</h5>
		    <h1 class="card-text text-center"><%= Item.sent(current_user).count%></h1>
		  </div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="card custom-card shadow-sm card-style">
		  <div class="card-body">
		    <h5 class="card-title text-center">Total items delivered</h5>
		    <h1 class="card-text text-center"><%= Item.delivered(current_user).count%></h1>
		  </div>
		</div>
	</div>
	<div class="col-lg-4">
		<%= link_to pending_buyer_comments_path do %>		
			<div class="card custom-card shadow-sm card-style">
			  <div class="card-body">
			    <h5 class="card-title text-center">Pending vendor comments</h5>
			    <h1 class="card-text text-center"><%= Item.pending_buyer_comments(current_user).count%></h1>
			  </div>
			</div>
		<% end %>
	</div>
</div>
<div class="row mt-20">
	<div class="col-lg-4">
		<%= link_to buyer_approved_items_path do %>	
			<div class="card custom-card shadow-sm card-style">
			  <div class="card-body">
			    <h5 class="card-title text-center">Total items approved</h5>
			    <h1 class="card-text text-center"><%= Item.approved(current_user).count%></h1>
			  </div>
			</div>
		<% end %>
	</div>
	<div class="col-lg-4">
		<%= link_to pending_buyer_approval_path do %>		
			<div class="card custom-card shadow-sm card-style">
			  <div class="card-body">
			    <h5 class="card-title text-center">Total approval clarification pending</h5>
			    <h1 class="card-text text-center"><%= Item.pending(current_user).count%></h1>
			  </div>
			</div>
		<% end %>
	</div>
</div>