config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'registrations' }
	root to: 'home#index'
	resources :buyers do 
		member do
			get :pending_buyer_comments
			post :update_pending_buyer_comments
			get :pending_buyer_approval
			post :update_pending_buyer_approval
			get :buyer_approved_items
			post :update_buyer_approved_items
		end
		resources :couriers do 
   		member do
   			get 'sample_type_items'
   			get 'approve_status'
   		end
   		resources :items do
   			collection do
	   			get 'delete_multiple_items'
	   			post 'save_items'
	   			get 'edit_delivery_items'
	   			post 'update_delivery_items'
				end
   		end
		end
		member do 
			get 'get_teams'
		end
		resources :teams do
			resources :team_members
		end
	end
	resources :users
	resources :sample_types
	get 'reports', to: 'reports#index'
	get 'download_report', to: 'reports#download_report'
	get 'send_reminder_mail', to: 'items#send_reminder_mail'
	get 'all_couriers', to: 'couriers#all_couriers'
	get 'new_courier', to: 'couriers#new_courier'
	post 'save_courier', to: 'couriers#save_courier'
	get 'undelivered_couriers', to: 'couriers#undelivered_couriers'
	post 'update_courier_delivery_dates', to: 'couriers#update_courier_delivery_dates'
	get 'pending_buyer_comments', to: 'items#pending_buyer_comments'
	get 'pending_buyer_approval', to: 'items#pending_buyer_approval'
	get 'buyer_approved_items', to: 'items#buyer_approved_items'
end

app/models/courier.rb
class Courier < ApplicationRecord

	belongs_to :buyer
	belongs_to :team
	has_many :items, dependent: :destroy
	has_one_attached :airway_bill_image

	validates :airway_bill_number, {presence: true, uniqueness: {case_sensitive: true}, length: {minimum: 3, maximum: 75}}
	validates :courier_date, presence: true
	validates :number_of_items, numericality: { greater_than_or_equal_to: 1 }

	def team_name
		team.present? ? team.name : '-'
	end

	def self.sent user
		where.not(courier_date: nil).where(buyer_id: user.buyer_ids)
	end

	def self.pending_delivery user
		where(approved: true, delivery_date: nil, buyer_id: user.buyer_ids)
	end

	def self.delivered user
		where.not(delivery_date: nil).where(buyer_id: user.buyer_ids)
	end

	def self.buyer_delivered buyer, user
		delivered(user).where(buyer_id: buyer.id)
	end

end

app/models/team.rb
class Team < ApplicationRecord

	belongs_to :buyer
	has_many :couriers
	has_many :team_members, dependent: :destroy

	validates :name, {presence: true, uniqueness: {case_sensitive: true}, length: {minimum: 3, maximum: 75}}
	
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController

	before_action :set_buyer, except: [:all_couriers, :new_courier, :save_courier, :undelivered_couriers, :update_courier_delivery_dates]
	before_action :set_courier, except: [:index, :new, :create, :all_couriers, :new_courier, :save_courier, :undelivered_couriers, :update_courier_delivery_dates]

	def index
		@couriers = @buyer.couriers.order(:courier_date).includes(:team)
		respond_to do |format|
  		format.js {render file: "couriers/index.js.erb"}
  		format.html{}
  	end
	end

	def new
		@courier = Courier.new
		@buyer_id = params[:buyer_id]
		@buyers = current_user.buyers
	end

	def create
		@buyers = Buyer.order(:name)
		@courier = Courier.new(courier_params)
		if @courier.save
			redirect_to sample_type_items_buyer_courier_path(@buyer, @courier), notice: "Courier was successfully created."
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to buyer_couriers_path(@buyer), notice: "Courier was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js
      end
    end
  end

	def show
		@approved = @courier.approved
		@has_items = @courier.items.present?
		respond_to do |format|
	      format.js {render file: "items/index.js.erb"}
	      format.html { }
	    end
	end

	def sample_type_items
		@sample_types = SampleType.order(:name)
		@items = @courier.items.where(sample_type_id: params[:sample_type_id]).sort_by{|c| c.serial_number.to_i}
		respond_to do |format|
      format.js {render file: "couriers/sample_type_items.js.erb"}
      format.html {}
      format.json { render file: "couriers/sample_type_items.js.erb" }
    end
	end

	def approve_status
		@courier.update(approved: true)
		redirect_to buyer_courier_path(@buyer, @courier), notice: "Courier was successfully approved and mail was sent to the team members."
		CourierMailer.send_mail(@courier).deliver_later
	end

	def destroy
		@courier.destroy
		redirect_to buyer_couriers_path(@buyer), notice: "Courier was successfully deleted."
	end

	def all_couriers
		buyers_ids = current_user.buyer_ids
		@couriers = Courier.where(buyer_id: buyers_ids).order(:courier_date).includes(:buyer, :team, :items)
	end

	def new_courier
		@buyers = current_user.buyers
		@courier = Courier.new
	end

	def save_courier
		@buyers = current_user.buyers
		@courier = Courier.new(courier_params)
		if @courier.save
			redirect_to sample_type_items_buyer_courier_path(@courier.buyer, @courier), notice: "Courier was successfully created."
		else
			render :new_courier, status: :unprocessable_entity
		end
	end

	def undelivered_couriers
		@undelivered_couriers = Courier.pending_delivery(current_user).includes(:team)
	end

	def update_courier_delivery_dates
		couriers = Courier.where(id: params[:courier_ids].keys)
		delivery_date = Date.new(params[:delivery_date]['(1i)'].to_i,params[:delivery_date]['(2i)'].to_i,params[:delivery_date]['(3i)'].to_i) rescue Date.today
		couriers.update(delivery_date: delivery_date)
		redirect_to undelivered_couriers_path, notice: 'Delivery Date updated successfully.'
	end

	private

	def courier_params
		params.require(:courier).permit(:airway_bill_number, :buyer_comments, :buyer_id, :courier_date, :description, :received_status, :approved, :team_id, :delivery_date, :number_of_items, :airway_bill_image)
	end

	def set_courier
		@courier = Courier.find(params[:id])
	end

	def set_buyer
      @buyer = Buyer.find(params[:buyer_id])
    end
end

app/helpers/couriers_helper.rb
module CouriersHelper

	def courier_date_display courier
		courier.courier_date.present? ? date_display(courier.courier_date) : '-'
	end

	def delivery_date_display courier
		courier.delivery_date.present? ? date_display(courier.delivery_date) : fa_pending
	end

	def approved_display courier
		courier.approved ? fa_approved : fa_pending
	end

end

app/views/couriers/_courier_items.html.erb
<div class="tableFixHead mt-20">
  <table class="table table-striped" id="courier_items">
    <thead class="thead-dark">
      <tr>
        <th scope="col">S.No</th>
        <th scope="col">Sample Type</th>
        <th scope="col">Description</th>
        <th scope="col">No of samples</th>
        <th scope="col">Photo</th>
        <th scope="col">Vendor comments</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @has_items %>
        <% @courier.items.includes(:sample_type).sort_by{|c| c.serial_number.to_i}.each do |item| %>
          <tr>
            <td><%= item.serial_number %></td>
            <td><%= item.sample_type_name %></td>
            <td><%= item.description %></td>
            <td><%= item.number_of_samples %></td>
            <% if item.item_image.attached? && item.item_image.content_type != "application/pdf" %>
              <td><%= image_tag item.item_image.variant(resize: "100x100")%></td>
            <% else %>
              <td>No Preview available</td>
            <% end %>
            <td><%= item.buyer_comments.present? ? item.buyer_comments : 'NA' %></td>
            <% if @approved%>
              <td>
                <i class="fa fa-edit text-danger" disabled></i>
                <i class="fa fa-trash text-danger" disabled></i>
              </td>
            <% else%>
              <td>
                <%= link_to '', edit_buyer_courier_item_path(@buyer, @courier, item, courier_show_page: true), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'fa fa-edit'} %>
                <%= link_to '', buyer_courier_item_path(@buyer, @courier, item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="7" class="text-center">No items yet</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">

  var table = $('#courier_items').DataTable( {
    scrollY: 450,
    orderCellsTop: true,
    fixedColumns: true,
    fixedHeader: true,
    width: 100
  } );
</script>

app/views/couriers/_form.html.erb
<%= form_for([@buyer, @courier], remote: true) do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">Edit Courier</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div id="error_explanation"></div>
    <div class="form-group row">
      <label for="team" class="col-sm-4 col-form-label">Team</label>
      <%= f.select(:team_id, @buyer.teams.order(:name).pluck(:name, :id),  {prompt: "Select a team"}, {class: 'text-box-width'}) %>
    </div>
    <div class="form-group row">
      <label for="airway_bill_number" class="col-sm-4 col-form-label">Airway Bill No</label>
      <%= f.text_field :airway_bill_number %>
      <div style="margin-left: 10px;">
        <%#= f.file_field :airway_bill_image %>
      </div>
    </div>
    <div class="form-group row">
      <label for="description" class="col-sm-4 col-form-label">Description</label>
      <%= f.text_area :description, class: 'text-box-width' %>
    </div>
    <div class="form-group row">
      <label for="courier_date" class="col-sm-4 col-form-label">Courier Date</label>
      <%= f.date_select :courier_date %>
    </div>
    <div class="form-group row">
      <label for="number_of_items" class="col-sm-4 col-form-label">No of Items</label>
      <%= f.text_field :number_of_items %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
    <%= f.submit 'Save', class: "btn btn-success btn-sm"%>
  </div>
<% end %>

app/views/couriers/_index.html.erb
<table class="table table-striped" id="couriers">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Courier Date</th>
      <th scope="col">Airway Bill No</th>
      <th scope="col">Team</th>
      <th scope="col">Items</th>
      <th scope="col">Approved</th>
      <th scope="col">Delivered</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @couriers.present? %>
      <% @couriers.each do |courier| %>
        <tr>
          <td><%= courier_date_display(courier)%></td>
          <td><%= link_to courier.airway_bill_number, buyer_courier_path(@buyer, courier) %></td>
          <td><%= courier.team_name %></td>
          <td><%= courier.items.count %></td>
          <td><%= approved_display(courier) %></td>
          <td><%= delivery_date_display(courier) %></td>
          <% if courier.approved%>
            <td>
              <% unless courier.delivery_date.present?%>
                <%= link_to 'Add vendor comments', edit_delivery_items_buyer_courier_items_path(@buyer, courier) %>
              <% end %>
              <i class="fa fa-edit text-danger" disabled data-toggle='tooltip' data-placement='top' title='Cannot edit approved courier' ></i>
              <% if is_admin? %>
                <%= link_to '', buyer_courier_path(@buyer, courier), method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %>
              <% end %>
            </td>
          <% else %>
            <td>
              <%= link_to '', edit_buyer_courier_path(@buyer, courier), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'fa fa-edit'} %>
              <%= link_to '', buyer_courier_path(@buyer, courier), method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6" class="text-center">No couriers yet</td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">

  var table = $('#couriers').DataTable( {
    scrollY: 450,
    orderCellsTop: true,
    fixedColumns: true,
    fixedHeader: true,
    width: 100
  } );
</script>

app/views/couriers/_undelivered_couriers.html.erb
<style type="text/css">

table tbody {
  display: block;
  max-height: 400px;
  overflow-y: scroll;
}

table thead, table tbody tr {
  display: table;
  width: 100%;
  table-layout: fixed;
}
</style>
<%= form_tag update_courier_delivery_dates_path do %>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Select</th>
        <th scope="col">Airway Bill No</th>
        <th scope="col">Sent on</th>
        <th scope="col">Team</th>
        <th scope="col">No of items</th>
      </tr>
    </thead>
    <tbody>
      <% if @undelivered_couriers.present? %>
        <% @undelivered_couriers.each do |courier| %>
          <tr>
            <td><%= check_box_tag "courier_ids[#{courier.id}]", '', false, class: 'checkbox'%></td>
            <td><%= courier.airway_bill_number %></td>
            <td><%= courier.courier_date.present? ? courier.courier_date.strftime("%d-%m-%Y") : ''%></td>
            <td><%= courier.team_name %></td>
            <td><%= courier.items.length %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="5" class="text-center">All couriers delivered</td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div id="date_div" style="display: none;">
    <p id="selected" style="display: hidden;"></p>
    <div class="form-group row">
      <label for="delivery_date" class="col-sm-2 col-form-label">Delivery Date</label>
      <%= date_select 'delivery_date', '', class: 'delivery_date'%>
    </div>
    <%= submit_tag 'Save', id: 'submit', class: 'btn btn-success btn-sm'%>
  </div>
<% end %>
<script type="text/javascript">
  $('.checkbox').click(function(){
    if ($("input:checkbox:checked").length > 0)
    {
      $('#selected').html('Selected items - ');
      $('#date_div').show();
      $('#selected').append($("input:checkbox:checked").length + ' of '+ $("input:checkbox").length);
      $('#selected').show();
    }
    else
    {
      $('#date_div').hide();
    }
  })
</script>

app/views/couriers/all_couriers.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Couriers</h2>
      </div>
      <% if current_user.buyer_ids.length > 0 %>
        <div class="col text-right">
          <%= link_to 'New Courier', new_courier_path, class: 'btn btn-black btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="all_couriers_table" class="mt-10">
    <%= render partial: 'all_couriers'%>
  </div>
</div>

app/views/couriers/edit.js.erb
<%= render partial: 'layouts/form.js.erb'%>

app/views/couriers/form.js.erb
<%= render partial: 'layouts/form.js.erb'%>

app/views/couriers/index.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Couriers for <%= link_to @buyer.name, buyer_path(@buyer)%></h2>
      </div>
      <div class="col text-right">
        <%= link_to 'New Courier', new_buyer_courier_path(@buyer), class: 'btn btn-black btn-sm' %>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'index'%>
  </div>
</div>

<%= render partial: 'layouts/modal'%>

app/views/couriers/index.js.erb
$("#couriers_table").html("<%= j (render 'index') %>");
$("#exampleModalCenter").modal('toggle');
$("#notice_and_error").html("<%= j (render 'layouts/notice_and_error') %>");

app/views/couriers/new_courier.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Enter Courier Details</h2>
      </div>
    </div>
  </div>
  <div class="mt-10">
    <%= form_for(@courier, url: save_courier_path, method: :post, multipart: true) do |f| %>
      <div>
        <% if @courier.errors.any? %>
          <% @courier.errors.full_messages.each do |message| %>
            <div class='alert alert-danger alert-dismissible fade show' role='alert' style='margin-top: 10px;'>
              <%= message %><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="form-group row">
        <label for="buyer" class="col-sm-4 col-form-label">Vendor</label>
        <%= f.select(:buyer_id, @buyers.collect {|p| [p.name, p.id]}, {prompt: "Select a vendor"}, {class: 'text-box-width'}) %>
      </div>
      <div class="form-group row">
        <label for="team" class="col-sm-4 col-form-label">Team</label>
        <%= f.select(:team_id, Team.order(:name).collect {|p| [p.name, p.id]}, {}, {class: 'text-box-width'}) %>
      </div>
      <div class="form-group row">
        <label for="airway_bill_number" class="col-sm-4 col-form-label">Airway Bill No</label>
        <span style="display: inline-flex;">
          <%= f.text_field :airway_bill_number %>
          <%= f.file_field :airway_bill_image, class: 'form-control form-control-sm' %>
        </span>
      </div>
      <div class="form-group row">
        <label for="description" class="col-sm-4 col-form-label">Description</label>
        <%= f.text_area :description, class: 'text-box-width' %>
      </div>
      <div class="form-group row">
        <label for="courier_date" class="col-sm-4 col-form-label">Courier Date</label>
        <%= f.date_select :courier_date %>
      </div>
      <div class="form-group row">
        <label for="number_of_items" class="col-sm-4 col-form-label">No of items</label>
        <%= f.text_field :number_of_items %>
      </div>
      <div class="actions">
        <%= link_to 'Back to Couriers', all_couriers_path, class: 'btn btn-black btn-sm' %>
        <%= f.submit "Save and add Samples", class: "btn btn-success btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $("#courier_team_id").prop("disabled", true); // second dropdown is disable while first dropdown is empty
  $("#courier_team_id").empty();

  $("#courier_team_id").append('<option>Select a team</option>');
$("#courier_buyer_id").change(function(){
  var buyer_id = $(this).val();
  if(buyer_id == ''){
    $("#courier_team_id").prop("disabled", true);
    $("#courier_team_id").empty();

    $("#courier_team_id").append('<option>Select a team</option>');
  }else{
    $("#courier_team_id").prop("disabled", false);
    $.ajax({
      url: "/buyers/"+buyer_id+"/get_teams",
      method: "GET",  
      dataType: "json",
      data: {buyer_id: buyer_id},
      error: function (xhr, status, error) {
        console.error('AJAX Error: ' + status + error);
      },
      success: function (response) {
        console.log(response);
        var teams = response["teams"];
        $("#courier_team_id").empty();

        $("#courier_team_id").append('<option>Select a team</option>');
        for(var i = 0; i < teams.length; i++){
          $("#courier_team_id").append('<option value="' + teams[i]["id"] + '">' +teams[i]["name"] + '</option>');
        }
      }
    });
  }
});
</script>

app/views/couriers/sample_type_items.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Add Sample and Items</h2>
      </div>
    </div>
  </div>
  <div class="mt-10">
    <%= form_tag save_items_buyer_courier_items_path(@buyer, @courier), method: :post, multipart: true do %>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col" style="width: 10%">S.no</th>
            <th scope="col" style="width: 20%">Sample Type</th>
            <th scope="col" style="width: 30%">Description</th>
            <th scope="col" style="width: 10%">No of samples</th>
            <th scope="col" style="width: 30%">Photo</th>
          </tr>
        </thead>
        <tbody>
          <% 1.upto(@courier.number_of_items) do |number|%>
            <% item = @courier.items.find_by(serial_number: number)%>
            <tr>
              <%= hidden_field_tag "items[#{number}][courier_id]", @courier.id%>
              <%= hidden_field_tag "courier_id", @courier.id%>
              <td>
                <%= text_field_tag "items[#{number}][serial_number_display]", number, class: 'text-box-width', disabled: true %>
                <%= hidden_field_tag "items[#{number}][serial_number]", number%>
              </td>
              <td> 
                <%= select_tag("items[#{number}][sample_type_id]", options_from_collection_for_select(@sample_types, "id", "name", item.try(:sample_type_id)),  {prompt: "Select a sample type", style: 'width: 100%'}) %>
              </td>
              <td><%= text_area_tag "items[#{number}][description]", item.try(:description), style: 'width: 100%' %></td>
              <td><%= text_field_tag "items[#{number}][number_of_samples]", item.try(:number_of_samples), class: 'text-box-width' %></td>
              <td><%= file_field_tag "items[#{number}][item_image]", value: (rails_blob_path(item.item_image) if item && item.item_image.attached?), class: 'form-control form-control-sm' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="actions">
        <%= link_to "Back", buyer_courier_path(@buyer, @courier), class: "btn btn-black btn-sm" %>
        <%= link_to "Back to couriers", (is_admin? ? buyer_couriers_path(@buyer) : all_couriers_path), class: "btn btn-black btn-sm" %>
        <%= submit_tag "Save", class: "btn btn-success btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/couriers/sample_type_items.js.erb
$("#items_table").html("<%= j (render 'items/index') %>");
$("#exampleModalCenter").modal('hide');
$("#notice_and_error").html("<%= j (render 'layouts/notice_and_error') %>");

app/views/couriers/show.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
	<div class="card-header">
    <div class="row align-items-center">
      <div class="col">
      	<% if is_admin? %>
	      	<h2 class="h5">Vendor - <%= link_to @buyer.name, buyer_path(@buyer) %></h2>
				<% else %>
					<h2 class="h5">Vendor - <%= @buyer.name %></h2>
				<% end %>
      </div>
      <div class="col text-right">
      	<% if is_admin? %>
      	<%= link_to 'Delete', buyer_courier_path(@buyer, @courier), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
					<%= link_to 'Couriers', buyer_couriers_path(@buyer), class: 'btn btn-black btn-sm' %>
				<% else %>
					<%= link_to 'Couriers', all_couriers_path, class: 'btn btn-black btn-sm' %>
				<% end %>
        <% unless @courier.approved %>
					<%= link_to 'Add / Edit items', sample_type_items_buyer_courier_path(@buyer, @courier), class: 'btn btn-black btn-sm' %>
				<% end %>
				<% if @courier.approved %>
					<%= link_to 'Add / Edit Buyer Comments', edit_delivery_items_buyer_courier_items_path(@buyer, @courier), class: 'btn btn-black btn-sm' %>
				<% end %>
      </div>
    </div>
    <div class="row align-items-center mt-10">
  		<div class="col-lg-6">
    		<span class='col-lg-3'><b>Team </b></span> : <%= @courier.team_name%>
    	</div>
    	<div class="col-lg-6">
    		<% if @has_items %>
					<span class='col-lg-3'><b>Approval Status </b></span>
					<% if @approved %> 
						: <%= fa_approved %>
					<% elsif is_staff?%>
						: <%= fa_pending %> 
					<% else %>
						: <%= (link_to 'Approve', approve_status_buyer_courier_path(@buyer, @courier), class: 'btn btn-success btn-sm')%>
					<% end %>
				<% end %>
			</div>
    </div>
    <div class="row align-items-center mt-10">
    	<div class="col-lg-6">
				<span class='col-lg-3'><b> Airway Bill No </b></span> : <%= @courier.airway_bill_number%>
			</div>
			<div class="col-lg-6">
				<% if @has_items %>
					<span class='col-lg-3'><b>Delivery Status </b></span> 
					<% if @courier.delivery_date.present? %> 
						: <span style="color: green;"> Delivered on <%= delivery_date_display(@courier)%></span> 
					<% else %>
						: <%= fa_pending%>
					<% end %>
				<% end %>
			</div>
    </div>
		<% if @courier.airway_bill_image.attached? && @courier.airway_bill_image.content_type != "application/pdf" %>
			<div class="row align-items-center mt-10">
				<div class="col ml-15">
					<%= image_tag @courier.airway_bill_image.variant(resize: "100x100")%>
				</div>
			</div>
		<% end %>
  </div>
	<% if @has_items%>
		<div id="courier_items_table">
		  <%= render partial: 'courier_items'%>
		</div>
	<% else %>
		<h4 class="text-center mt-30">No items added yet</h4>
	<% end %>
</div>


<%= render partial: 'layouts/modal'%>

app/views/couriers/undelivered_couriers.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Undelivered Couriers</h2>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'undelivered_couriers'%>
  </div>
</div>