config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'registrations' }
	root to: 'home#index'
	resources :buyers do 
		member do
			get :pending_buyer_comments
			post :update_pending_buyer_comments
			get :pending_buyer_approval
			post :update_pending_buyer_approval
			get :buyer_approved_items
			post :update_buyer_approved_items
		end
		resources :couriers do 
   		member do
   			get 'sample_type_items'
   			get 'approve_status'
   		end
   		resources :items do
   			collection do
	   			get 'delete_multiple_items'
	   			post 'save_items'
	   			get 'edit_delivery_items'
	   			post 'update_delivery_items'
				end
   		end
		end
		member do 
			get 'get_teams'
		end
		resources :teams do
			resources :team_members
		end
	end
	resources :users
	resources :sample_types
	get 'reports', to: 'reports#index'
	get 'download_report', to: 'reports#download_report'
	get 'send_reminder_mail', to: 'items#send_reminder_mail'
	get 'all_couriers', to: 'couriers#all_couriers'
	get 'new_courier', to: 'couriers#new_courier'
	post 'save_courier', to: 'couriers#save_courier'
	get 'undelivered_couriers', to: 'couriers#undelivered_couriers'
	post 'update_courier_delivery_dates', to: 'couriers#update_courier_delivery_dates'
	get 'pending_buyer_comments', to: 'items#pending_buyer_comments'
	get 'pending_buyer_approval', to: 'items#pending_buyer_approval'
	get 'buyer_approved_items', to: 'items#buyer_approved_items'
end

app/models/item.rb
class Item < ApplicationRecord

	belongs_to :sample_type
	belongs_to :courier
	has_one_attached :item_image

	def sample_type_name
		sample_type.present? ? sample_type.name : '-'
	end

	def self.sent user
		where(courier_id: Courier.where(buyer_id: user.buyer_ids).ids)
	end

	def self.delivered user
		where(courier_id: Courier.delivered(user).ids)
	end

	def self.pending_buyer_comments user
		where(buyer_approved: '', courier_id: Courier.delivered(user).ids)
	end

	def self.approved user
		where(buyer_approved: 'Approved', courier_id: Courier.where(buyer_id: user.buyer_ids).ids)
	end

	def self.pending user
		where(buyer_approved: 'Pending', courier_id: Courier.where(buyer_id: user.buyer_ids).ids)
	end

	def self.pending_buyer_comments_with_buyer buyer, user
		where(buyer_approved: '', courier_id: Courier.buyer_delivered(buyer, user).ids)
	end

	def self.approved_with_buyer buyer, user
		where(buyer_approved: 'Approved', courier_id: Courier.buyer_delivered(buyer, user).ids)
	end

	def self.pending_with_buyer buyer, user
		where(buyer_approved: 'Pending', courier_id: Courier.buyer_delivered(buyer, user).ids)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :set_courier, except: [:send_reminder_mail, :pending_buyer_comments, :pending_buyer_approval, :buyer_approved_items]
	before_action :set_item, except: [:new, :create, :save_items, :delete_multiple_items, :edit_delivery_items, :update_delivery_items, :send_reminder_mail, :pending_buyer_comments, :pending_buyer_approval, :buyer_approved_items]

	def new
		@item = Item.new
		@sample_type_id = params[:sample_type_id]
		@courier_show_page = params[:courier_show_page]
	    respond_to do |format|
	      format.js {render file: "items/form.js.erb"}
	    end

	end

	def create
		@item = Item.new(item_params)
		redirect_path = params[:courier_show_page].present? ? buyer_courier_path(@buyer, @courier) : sample_type_items_buyer_courier_path(@buyer, @courier, sample_type_id: @item.sample_type_id)
		respond_to do |format|
	      if @item.save
	        format.html { redirect_to redirect_path, notice: "Item was successfully added." }
	      else
	        format.html { render :new, status: :unprocessable_entity }
	        format.js
	      end
	    end
	end

	def edit
		@sample_type_id = params[:sample_type_id]
		@courier_show_page = params[:courier_show_page]
		respond_to do |format|
	      format.js
	    end
	end

	def update
		redirect_path = params[:courier_show_page].present? ? buyer_courier_path(@buyer, @courier) : sample_type_items_buyer_courier_path(@buyer, @courier, sample_type_id: @item.sample_type_id)
		respond_to do |format|
	      if @item.update(item_params)
	        format.html { redirect_to redirect_path, notice: "Item was successfully updated." }
	      else
	        format.html { render :edit, status: :unprocessable_entity }
	        format.js
	      end
	    end
	end

	def destroy
		sample_type_id = @item.sample_type_id
		@item.destroy
		redirect_to buyer_courier_path(@buyer, @courier), notice: "Item was successfully deleted."
		@courier.items.where(sample_type_id: sample_type_id).order(:id).each_with_index do |item, index|
			item.update(serial_number: index+1)
		end
	end

	def save_items
		params[:items].values.each do |item_param|
			Item.find_or_create_by(serial_number: item_param['serial_number'], courier_id: params['courier_id']) do |item|
				item.description = item_param['description']
				item.sample_type_id = item_param['sample_type_id']
				item.number_of_samples = item_param['number_of_samples']
				item.item_image = item_param['item_image']
				item.save
			end
		end
		redirect_to buyer_courier_path(@buyer, @courier), notice: "Items were created successfully."
	end

	def edit_delivery_items
		@items = @courier.items.sort_by{|c| c.serial_number.to_i}
	end

	def update_delivery_items
		delivery_date = Date.new(params[:courier]['delivery_date(1i)'].to_i,params[:courier]['delivery_date(2i)'].to_i,params[:courier]['delivery_date(3i)'].to_i) rescue Date.today
		@courier.update(delivery_date: delivery_date)
		params[:items].each do |id, item_param|
			item = Item.find(id)
			item.buyer_comments = item_param['buyer_comments']
			item.received_status = true
			item.save
		end
		redirect_to buyer_courier_path(@buyer, @courier), notice: "Vendor comments were created successfully."
	end

	def delete_multiple_items
		@courier.items.where(sample_type_id: params[:sample_type_id]).destroy_all
		redirect_to buyer_courier_path(@buyer, @courier), notice: 'Sample type and items were successfully deleted.'
	end

	def send_reminder_mail
		if params[:from] == 'reports'
			send_all_items
			return_path = reports_path
		elsif params[:from] == 'pending_buyer_comments'
			send_all_items
			return_path = pending_buyer_comments_path
		else
			send_all_items(params[:id], params[:remarks])
			return_path = pending_buyer_comments_buyer_path(params[:id])
		end	
		respond_to do |format|
			format.html {redirect_to return_path, notice: 'Reminder mail successfully sent.'}
			format.json {render json: {status: 200, notice: 'Reminder mail successfully sent.'}}
		end
	end

	def send_all_items(buyer_id = nil, remarks = [])
    sent_couriers = if buyer_id.present? 
    	params[:remarks].each do |remark|
    		Item.find(remark[1].keys[0]).update(remarks: remark[1].values[0])
    	end
      Courier.buyer_delivered(Buyer.find(buyer_id), current_user)
    else
      Courier.delivered
    end
    mail_hash = {}
    sent_couriers.joins(:items).where(items: {buyer_approved: ''}).uniq.group_by(&:team). each do |team, couriers|
      mail_hash[team] = []
      couriers.each do |courier|
        mail_hash[courier.team] << courier.items.where(buyer_approved: '').sort_by{|c| c.serial_number.to_i}
      end
    end
    mail_hash.each do |team, items|
      SendReminderMailer.send_mail(team, items.flatten).deliver_later
    end
	end

	def pending_buyer_comments
		courier_ids = Item.pending_buyer_comments(current_user).pluck(:courier_id)
		@buyers_couriers = Courier.where(id: courier_ids).includes(:team, :items).group_by(&:buyer)
	end

	def pending_buyer_approval
		courier_ids = Item.pending(current_user).pluck(:courier_id)
		@buyers_couriers = Courier.where(id: courier_ids).includes(:team, :items).group_by(&:buyer)
	end

	def buyer_approved_items
		courier_ids = Item.approved(current_user).pluck(:courier_id)
		@buyers_couriers = Courier.where(id: courier_ids).includes(:team, :items).group_by(&:buyer)
	end

	private

	def item_params
		params.require(:item).permit(:serial_number, :description, :sample_type_id, :courier_id, :buyer_comments, :received_status, :number_of_samples, :item_image)
	end

	def set_courier
		@courier = Courier.find(params[:courier_id])
		@buyer = @courier.buyer
	end

	def set_item
		@item = Item.find(params[:id])
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_buyer_approved_items.html.erb
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Vendor</th>
      <th scope="col">Airway Bill No</th>
      <th scope="col">Team</th>
      <th scope="col">Delivered On</th>
      <th scope="col">Approved items</th>
    </tr>
  </thead>
  <tbody>
    <% if @buyers_couriers.present? %>
      <% @buyers_couriers.each do |buyer, couriers| %>
        <tr>
          <td rowspan="<%= couriers.length+1%>" style='text-align: center;vertical-align: middle'><%= link_to buyer.name, buyer_approved_items_buyer_path(buyer) %></td>
          <% couriers.each do |courier| %>
            <tr>
            <td><%= courier.airway_bill_number %></td>
            <td><%= courier.team_name %></td>
            <td><%= delivery_date_display(courier)%></td>
            <td><%= courier.items.where(buyer_approved: 'Approved').length %></td>
          </tr>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5" class="text-center">No approved items</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/_form.html.erb
<%= form_for([@buyer, @courier, @item], remote: true) do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle"><%= @item.serial_number.present? ? 'Edit' : 'Add'%> Item</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div id="error_explanation"></div>
    <%= hidden_field_tag 'item[courier_id]', @courier.id%>
    <div class="form-group row">
      <label for="serial_number" class="col-sm-4 col-form-label">S.no</label>
      <%= f.text_field :serial_number, disabled: true %>
    </div>
    <%= hidden_field_tag 'item[serial_number]', @item.serial_number%>
    <div class="form-group row">
      <label for="description" class="col-sm-4 col-form-label">Description</label>
      <%= f.text_area :description, class: 'text-box-width' %>
    </div>
    <div class="form-group row">
      <label for="number_of_samples" class="col-sm-4 col-form-label">No of samples</label>
      <%= f.text_field :number_of_samples %>
    </div>
  </div>
  <%= hidden_field_tag 'item[sample_type_id]', @item.sample_type_id.present? ? @item.sample_type_id : @sample_type_id%>
  <%= hidden_field_tag 'courier_show_page', @courier_show_page%>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit 'Save', class: "btn btn-success"%>
  </div>
<% end %>

app/views/items/_index.html.erb
<table class="table table-striped">
<thead class="thead-dark">
  <tr>
    <th scope="col">S.no</th>
    <th scope="col">Description</th>
    <!-- <th scope="col">Photo</th> -->
    <th scope="col" colspan="2">Actions</th>
  </tr>
</thead>
<tbody>
  <% if @items.present? %>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.serial_number %></td>
        <td><%= item.description %></td>
        <!-- <td>Photo</td> -->
        <td><%= link_to 'Edit', edit_buyer_courier_item_path(@buyer, @courier, item, sample_type_id: item.sample_type_id), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></td>
        <td><%= link_to 'Destroy', buyer_courier_item_path(@buyer, @courier, item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="4" class="text-center">No items yet</td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/items/_pending_buyer_approval.html.erb
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Vendor</th>
      <th scope="col">Airway Bill No</th>
      <th scope="col">Team</th>
      <th scope="col">Delivered On</th>
      <th scope="col">Pending items</th>
    </tr>
  </thead>
  <tbody>
    <% if @buyers_couriers.present? %>
      <% @buyers_couriers.each do |buyer, couriers| %>
        <tr>
          <td rowspan="<%= couriers.length+1%>" style='text-align: center;vertical-align: middle'><%= link_to buyer.name, pending_buyer_approval_buyer_path(buyer) %></td>
          <% couriers.each do |courier| %>
            <tr>
            <td><%= courier.airway_bill_number %></td>
            <td><%= courier.team_name %></td>
            <td><%= delivery_date_display(courier)%></td>
            <td><%= courier.items.where(buyer_approved: 'Pending').length %></td>
          </tr>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5" class="text-center">No pending items</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/_pending_buyer_comments.html.erb
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Vendor</th>
      <th scope="col">Airway Bill No</th>
      <th scope="col">Team</th>
      <th scope="col">Delivered On</th>
      <th scope="col">No of items pending</th>
    </tr>
  </thead>
  <tbody>
    <% if @buyers_couriers.present? %>
      <% @buyers_couriers.each do |buyer, couriers| %>
        <tr>
          <td rowspan="<%= couriers.length+1%>" style='text-align: center;vertical-align: middle'><%= link_to buyer.name, pending_buyer_comments_buyer_path(buyer) %>
          </td>
          <% couriers.each do |courier| %>
            <tr>
            <td><%= courier.airway_bill_number %></td>
              <td><%= courier.team_name %></td>
              <td><%= delivery_date_display(courier)%></td>
              <td><%= courier.items.where(buyer_approved: '').length %></td>
            </tr>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5" class="text-center">No vendors with pending comments</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/create.js.erb
<%= render partial: 'layouts/error.js.erb', locals: {item: @item}%>

app/views/items/edit.js.erb
$("#exampleModalCenter").find(".modal-content").html("<%= j (render 'form') %>");
$("#exampleModalCenter").modal();

app/views/items/edit_delivery_items.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Add/Edit Vendor Comments</h2>
      </div>
    </div>
  </div>
  <div class="mt-10">
    <%= form_tag update_delivery_items_buyer_courier_items_path(@buyer, @courier), method: :post do %>
      <div class="form-group row">
        <label for="delivery_date" class="col-sm-4 col-form-label">Courier Delivery Date</label>
        <%= date_select('courier', 'delivery_date', selected: @courier.delivery_date) %>
      </div>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">S.no</th>
            <th scope="col">Sample Type</th>
            <th scope="col">Vendor Comment</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item|%>
            <tr>
              <%= hidden_field_tag "courier_id", @courier.id%>
              <td>
                <%= item.serial_number %>
              </td>
              <td> 
                <%= item.sample_type.name %>             
              </td>
              <td><%= text_area_tag "items[#{item.id}][buyer_comments]", item.try(:buyer_comments), class: 'text-box-width' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="actions">
        <%= link_to "Back", buyer_courier_path(@buyer, @courier), class: "btn btn-black btn-sm" %>
        <%= link_to "Back to couriers", (is_admin? ? buyer_couriers_path(@buyer) : all_couriers_path), class: "btn btn-black btn-sm" %>
        <%= submit_tag "Save", class: "btn btn-success btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/form.js.erb
<%= render partial: 'layouts/form.js.erb'%>

app/views/items/index.js.erb
$("#courier_items_table").html("<%= j (render 'couriers/courier_items') %>");
$("#exampleModalCenter").modal('toggle');
$("#notice_and_error").html("<%= j (render 'layouts/notice_and_error') %>");

app/views/items/pending_buyer_approval.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Item wise pending Vendor Approval</h2>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'pending_buyer_approval'%>
  </div>
</div>

app/views/items/pending_buyer_comments.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Item wise pending Vendor Comments</h2>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'pending_buyer_comments'%>
  </div>
</div>

app/views/items/pending_items.pdf.erb
<% @items.group_by(&:courier).each do |courier, items| %>
	<% @company = courier.buyer.company%>
	<div class="new-page"></div>
	<%= render partial: 'layouts/header', locals: {company: @company}%>
	<h2>Airway Bill Number: <%= courier.airway_bill_number %></h2>
	<h5>Delivered on: <%= courier.delivery_date.present? ? courier.delivery_date.strftime("%d-%m-%Y") : ''%></h5>
	<br/>
	<h2><u>Items</u></h2>
	<% items.sort_by{|c| c.serial_number.to_i}.each_with_index do |item, index|%>
		<% if index > 0%>
			<div class="new-page"></div>
			<%= render partial: 'layouts/header', locals: {company: @company}%>
		<% end %>
		<table class="table table-striped">
			<thead class="thead-dark">
			  <tr>
			    <th>S.no</th>
			    <th>Sample Type</th>
			    <th>Description</th>
			    <th>No Of samples</th>
			    <th>Remarks</th>
			  </tr>
			</thead>
			<tbody>
	      <tr>
	        <td><%= index+1 %></td>
	        <td><%= item.sample_type_name %></td>
	        <td><%= item.description %></td>
	        <td><%= item.number_of_samples %></td>
	        <td><%= item.remarks %></td>
	      </tr>
			</tbody>
		</table>
		<% if item.item_image.attached? && item.item_image.content_type != "application/pdf" %>
          <p><%= image_tag url_for(item.item_image.variant(resize: "800x800"))%></p>
        <% else %>
          <p>No Preview available</p>
        <% end %>
		<br/>
		<hr/>
		<br/>
	<% end %>
	<br/>
	<hr/>
	<hr/>
	<br/>
<% end %>

<style type="text/css">
.new-page{
        page-break-before: always;
    }
.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 1rem;
    background-color: transparent;
}
.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}
.table td, .table th {
    padding: .75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}
th, td {
    text-align: center;
}
th {
    display: table-cell;
    /*vertical-align: inherit;*/
    font-weight: bold;
    /*text-align: -internal-center;*/
    background-color: #76abff;
}
thead {
    display: table-header-group;
    vertical-align: middle;
    border-color: inherit;
}
</style>

app/views/items/sample_photos.pdf.erb
<% @company = @courier.buyer.company%>
<%= render partial: 'layouts/header', locals: {company: @company} %>
<h2 style="text-align: center;">ITEMS LIST</h2>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<h3>Airway Bill Number: <%= @courier.airway_bill_number %></h3>
<% if @courier.airway_bill_image.attached? && @courier.airway_bill_image.content_type != "application/pdf" %>
    <p><%= image_tag url_for(@courier.airway_bill_image.variant(resize: "400x400")) %></p>
<% else %>
    <p>No Preview available</p>
<% end %>
<br/>
<div class="new-page"></div>
<%= render partial: 'layouts/header', locals: {company: @company} %>
<h3><u>Items</u></h3>
<% @items.each_with_index do |item, index| %>
	<div class="<%= index != 0 ? 'new-page' : ''%>">
        <% if index != 0%>
            <%= render partial: 'layouts/header', locals: {company: @company} %>
        <% end %>
    <table class="table table-striped">
		<thead class="thead-dark">
		  <tr>
		    <th>S.no</th>
		    <th>Sample Type</th>
		    <th>Description</th>
		    <th>No Of samples</th>
		  </tr>
		</thead>
		<tbody>
      <tr>
        <td><%= item.serial_number %></td>
        <td><%= item.sample_type.name %></td>
        <td><%= item.description %></td>
        <td><%= item.number_of_samples %></td>
      </tr>
		</tbody>
	</table>
    <% if item.item_image.attached? && item.item_image.content_type != "application/pdf" %>
	   <p><%= image_tag url_for(item.item_image.variant(resize: "800x800")) %></p>
    <% else %>
        <p>No Preview available</p>
    <% end %>
</div>
<% end %>

<style type="text/css">
.new-page{
        page-break-before: always;
    }
.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 1rem;
    background-color: transparent;
}
.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}
.table td, .table th {
    padding: .75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}
th, td {
    text-align: center;
}
th {
    display: table-cell;
    /*vertical-align: inherit;*/
    font-weight: bold;
    /*text-align: -internal-center;*/
    background-color: #76abff;
}
thead {
    display: table-header-group;
    vertical-align: middle;
    border-color: inherit;
}
</style>