config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'registrations' }
	root to: 'home#index'
	resources :buyers do 
		member do
			get :pending_buyer_comments
			post :update_pending_buyer_comments
			get :pending_buyer_approval
			post :update_pending_buyer_approval
			get :buyer_approved_items
			post :update_buyer_approved_items
		end
		resources :couriers do 
   		member do
   			get 'sample_type_items'
   			get 'approve_status'
   		end
   		resources :items do
   			collection do
	   			get 'delete_multiple_items'
	   			post 'save_items'
	   			get 'edit_delivery_items'
	   			post 'update_delivery_items'
				end
   		end
		end
		member do 
			get 'get_teams'
		end
		resources :teams do
			resources :team_members
		end
	end
	resources :users
	resources :sample_types
	get 'reports', to: 'reports#index'
	get 'download_report', to: 'reports#download_report'
	get 'send_reminder_mail', to: 'items#send_reminder_mail'
	get 'all_couriers', to: 'couriers#all_couriers'
	get 'new_courier', to: 'couriers#new_courier'
	post 'save_courier', to: 'couriers#save_courier'
	get 'undelivered_couriers', to: 'couriers#undelivered_couriers'
	post 'update_courier_delivery_dates', to: 'couriers#update_courier_delivery_dates'
	get 'pending_buyer_comments', to: 'items#pending_buyer_comments'
	get 'pending_buyer_approval', to: 'items#pending_buyer_approval'
	get 'buyer_approved_items', to: 'items#buyer_approved_items'
end

app/models/buyer.rb
class Buyer < ApplicationRecord

	COMPANY = ['Eclat International', 'Banumathi Exports']
	EMAILS = ['merch@banumathiexports.com']

	has_many :couriers, dependent: :destroy
	has_many :teams, dependent: :destroy
	
	validates :name, {presence: true, uniqueness: {case_sensitive: true}, length: {minimum: 3, maximum: 75}}
	validates :address, {presence: true, length: {minimum: 3, maximum: 500}}

	after_save :add_buyer_to_admin

	def add_buyer_to_admin
		admin = User.first
		unless admin.buyer_ids.include?(self.id)
			admin.buyer_ids.push(self.id)
			admin.save
		end
	end

	def company_upcase
		company.upcase
	end

	def is_eclat
		company == COMPANY[0]
	end

end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[ show edit update destroy get_teams pending_buyer_comments update_pending_buyer_comments pending_buyer_approval update_pending_buyer_approval buyer_approved_items update_buyer_approved_items]

  def index
    unless current_user.is_admin
      redirect_to root_path
    end
    @buyers = Buyer.all.includes(:teams, :couriers)
    respond_to do |format|
      format.js {render file: "buyers/index.js.erb"}
      format.html { }
    end
  end

  def show
    respond_to do |format|
      format.js {render file: "teams/index.js.erb"}
      format.html { }
    end
  end

  def new
    @buyer = Buyer.new
    respond_to do |format|
      format.js
    end 
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @buyer = Buyer.new(buyer_params)
    respond_to do |format|
      if @buyer.save
        format.html { redirect_to buyers_path, notice: "Vendor was successfully created." }
        format.js {redirect_to buyers_path, notice: "Vendor was successfully created."}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to buyers_path, notice: "Vendor was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: "Vendor was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def get_teams
    teams = @buyer.teams
    if request.xhr?
      respond_to do |format|
        format.json {
          render json: {teams: teams}
        }
      end
    end
  end

  def pending_buyer_comments
    @items = Item.pending_buyer_comments_with_buyer(@buyer, current_user).includes(:courier, :sample_type)
  end

  def update_pending_buyer_comments
    ids = params[:items][:id].keys
    ids.each do |id|
      item = Item.find(id)
      item.update(buyer_approved: params[:items][:buyer_approved][id])
    end
    redirect_to pending_buyer_comments_buyer_path(@buyer.id), notice: 'Vendor Comments updated successfully.'
  end

  def pending_buyer_approval
    @items = Item.pending_with_buyer(@buyer, current_user).includes(:courier, :sample_type)
  end

  def update_pending_buyer_approval
    ids = params[:items][:id].keys
    Item.where(id: ids).update_all(buyer_approved: 'Approved')
    redirect_to pending_buyer_approval_buyer_path(@buyer.id), notice: 'Vendor Approval updated successfully.'
  end

  def buyer_approved_items
    @items = Item.approved_with_buyer(@buyer, current_user).includes(:courier, :sample_type)
  end

  def update_buyer_approved_items
    ids = params[:items][:id].keys
    ids.each do |id|
      item = Item.find(id)
      item.update(buyer_approved: 'Pending')
    end
    redirect_to buyer_approved_items_buyer_path(@buyer.id), notice: 'Items made to Pending successfully.'
  end

  private
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    def buyer_params
      params.require(:buyer).permit(:name, :address, :company, :email)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_buyer_approved_items.html.erb
<style type="text/css">

table tbody {
  display: block;
  max-height: 400px;
  overflow-y: scroll;
}

table thead, table tbody tr {
  display: table;
  width: 100%;
  table-layout: fixed;
}
</style>

<%= form_tag update_buyer_approved_items_buyer_path do %>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Select</th>
      <th>Airway Bill No</th>
      <th>Delivered On</th>
      <th>Description</th>
      <th>Sample Type</th>
      <th>No of items</th>
      <th>Photo</th>
      <th>Vendor Comments</th>
    </tr>
  </thead>
  <tbody>
    <% if @items.present? %>
      <% @items.each do |item| %>
        <tr>
          <td><%= check_box_tag "items[id][#{item.id}", '', false, class: 'checkbox'%></td>
          <td><%= item.courier.airway_bill_number %></td>
          <td><%= delivery_date_display(item.courier)%></td>
          <td><%= item.description%></td>
          <td><%= item.sample_type_name %></td>
          <td><%= item.number_of_samples %></td>
          <% if item.item_image.attached? && item.item_image.content_type != "application/pdf" %>
            <td><%= image_tag item.item_image.variant(resize: "100x100")%></td>
          <% else %>
            <td>No Preview available</td>
          <% end %>
          <td><%= item.buyer_comments %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="8" class="text-center">No approved items</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= hidden_field_tag 'buyer_id', @buyer.id%>
<div id="submit_div" style="display: none;">
  <p id="selected" style="display: hidden;"></p>
  <%= submit_tag 'Reject', id: 'submit', class: 'btn btn-success btn-sm'%>
</div>
<% end %>
<script type="text/javascript">
  $('.checkbox').click(function(){
    if ($("input:checkbox:checked").length > 0)
    {
      $('#selected').html('Selected items - ');
      $('#submit_div').show();
      $('#selected').append($("input:checkbox:checked").length + ' of '+ $("input:checkbox").length);
      $('#selected').show();
    }
    else
    {
      $('#submit_div').hide();
    }
  })
</script>

app/views/buyers/_index.html.erb
<table class="table table-striped" id="buyers">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Company</th>
      <th scope="col">Email</th>
      <th scope="col">Teams</th>
      <th scope="col">Couriers</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @buyers.present? %>
      <% @buyers.each do |buyer| %>
        <tr>
          <td><%= link_to buyer.name, buyer %></td>
          <td><%= buyer.company %></td>
          <td><%= buyer.email %></td>
          <td><%= buyer.teams.length %></td>
          <td><%= buyer.couriers.length %></td>
          <td>
            <%= link_to '', edit_buyer_path(buyer), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'fa fa-edit'} %>
            <%= link_to '', buyer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash' %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4" class="text-center">No vendors yet</td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">

  var table = $('#buyers').DataTable( {
    scrollY: 450,
    orderCellsTop: true,
    fixedColumns: true,
    fixedHeader: true,
    width: 100
  } );
</script>

app/views/buyers/_pending_buyer_approval.html.erb
<style type="text/css">

table tbody {
  display: block;
  max-height: 400px;
  overflow-y: scroll;
}

table thead, table tbody tr {
  display: table;
  width: 100%;
  table-layout: fixed;
}
</style>

<%= form_tag update_pending_buyer_approval_buyer_path do %>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Select</th>
      <th>Airway Bill No</th>
      <th>Delivered On</th>
      <th>Description</th>
      <th>Sample Type</th>
      <th>No of items</th>
      <th>Photo</th>
    </tr>
  </thead>
  <tbody>
    <% if @items.present? %>
      <% @items.includes(:courier, :sample_type).each do |item| %>
        <tr>
          <td><%= check_box_tag "items[id][#{item.id}", '', false, class: 'checkbox'%></td>
          <td><%= item.courier.airway_bill_number %></td>
          <td><%= delivery_date_display(item.courier)%></td>
          <td><%= item.description%></td>
          <td><%= item.sample_type_name %></td>
          <td><%= item.number_of_samples %></td>
          <% if item.item_image.attached? && item.item_image.content_type != "application/pdf" %>
            <td><%= image_tag item.item_image.variant(resize: "100x100")%></td>
          <% else %>
            <td>No Preview available</td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="8" class="text-center">No pending comments</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= hidden_field_tag 'buyer_id', @buyer.id%>
<div id="submit_div" style="display: none;">
  <p id="selected" style="display: hidden;"></p>
  <%= submit_tag 'Approve', id: 'submit', class: 'btn btn-success btn-sm'%>
</div>
<% end %>
<script type="text/javascript">
  $('.checkbox').click(function(){
    if ($("input:checkbox:checked").length > 0)
    {
      $('#selected').html('Selected items - ');
      $('#submit_div').show();
      $('#selected').append($("input:checkbox:checked").length + ' of '+ $("input:checkbox").length);
      $('#selected').show();
    }
    else
    {
      $('#submit_div').hide();
    }
  })
</script>

app/views/buyers/_pending_buyer_comments.html.erb
<style type="text/css">

table tbody {
  display: block;
  max-height: 400px;
  overflow-y: scroll;
}

table thead, table tbody tr {
  display: table;
  width: 100%;
  table-layout: fixed;
}
</style>
<div id="message"></div>
<button class='btn btn-black btn-sm mb-10' id="send_reminder_mail">Send reminder mail</button>
<%= form_tag update_pending_buyer_comments_buyer_path do %>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Select</th>
      <th>Airway Bill No</th>
      <th>Delivered On</th>
      <th>Description</th>
      <th>Sample Type</th>
      <th>Items</th>
      <th>Photo</th>
      <th>Approval</th>
      <th>Remarks</th>
    </tr>
  </thead>
  <tbody>
    <% if @items.present? %>
      <% @items.each do |item| %>
        <tr>
          <td><%= check_box_tag "items[id][#{item.id}]", '', false, class: 'checkbox'%></td>
          <td><%= item.courier.airway_bill_number %></td>
          <td><%= delivery_date_display(item.courier) %></td>
          <td><%= item.description%></td>
          <td><%= item.sample_type_name %></td>
          <td><%= item.number_of_samples %></td>
          <% if item.item_image.attached? && item.item_image.content_type != "application/pdf" %>
            <td><%= image_tag item.item_image.variant(resize: "100x100")%></td>
          <% else %>
            <td>No Preview available</td>
          <% end %>
          <td><%= select_tag "items[buyer_approved][#{item.id}]", options_for_select(['Select', 'Approved', 'Pending'])%></td>
          <td><%= text_field_tag "remarks[#{item.id}]", '', style: 'width: 100%', class: 'remarks'%></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="9" class="text-center">No items with pending comments</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= hidden_field_tag 'buyer_id', @buyer.id%>
<div id="submit_div" style="display: none;">
  <p id="selected" style="display: hidden;"></p>
  <%= submit_tag 'Save', id: 'submit', class: 'btn btn-success btn-sm'%>
</div>
<% end %>
<script type="text/javascript">
  $('.checkbox').click(function(){
    if ($("input:checkbox:checked").length > 0)
    {
      $('#selected').html('Selected items - ');
      $('#submit_div').show();
      $('#selected').append($("input:checkbox:checked").length + ' of '+ $("input:checkbox").length);
      $('#selected').show();
    }
    else
    {
      $('#submit_div').hide();
    }
  })

  $('#submit').on('click', function (e) {
    $("input:checked").each(function () {
        var id = $(this).attr("id").split('_')[2];
        if($('#items_buyer_approved_'+id).val() == 'Select'){
          alert('Select the approval status for all checked items');
          e.preventDefault();
          return false;
        }
    });
  })

  $('#send_reminder_mail').click(function(){
    var remarks = []
    $('.remarks').each(function(){
      var remarks_hash = {}
      remarks_hash[$(this).attr('id').split('_')[1]] = this.value;
      remarks.push(remarks_hash)
    })
    $.ajax({
      url: "/send_reminder_mail",
      method: "GET",  
      dataType: "json",
      data: {id: <%= @buyer.id%>, from: 'pending_buyer_comments_buyer', remarks: remarks },
      error: function (xhr, status, error) {
        console.error('AJAX Error: ' + status + error);
      },
      success: function (response) {
        $('#message').append(
          '<div class="alert alert-success alert-dismissable">'+
            '<button type="button" class="close" data-dismiss="alert">'+
                '<span aria-hidden="true">&times;</span>'+
                '<span class="sr-only">Close</span>'+
            '</button>'+
            response.notice+
          '</div>'
        );
        $('.remarks').each(function(){
          this.value = '';
        })
      }
    });
  })
</script>

app/views/buyers/buyer_approved_items.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5"><%= @buyer.name%> - Approved items</h2>
      </div>
      <div class="col text-right">
        <%= link_to 'Back', buyer_approved_items_path, class: 'btn btn-black btn-sm' %>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'buyer_approved_items'%>
  </div>
</div>

app/views/buyers/create.js.erb
<%= render partial: 'layouts/error.js.erb', locals: {item: @buyer}%>

app/views/buyers/edit.js.erb
<%= render partial: 'layouts/form.js.erb' %>

app/views/buyers/form.js.erb
<%= render partial: 'layouts/form.js.erb'%>

app/views/buyers/index.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Vendors</h2>
      </div>
      <div class="col text-right">
        <%= link_to 'New Vendor', new_buyer_path, {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-black btn-sm'} %>
      </div>
    </div>
  </div>
  <div id="buyers_table" class="mt-10">
    <%= render partial: 'index'%>
  </div>
</div>

<%= render partial: 'layouts/modal'%>

app/views/buyers/new.js.erb
<%= render partial: 'layouts/form.js.erb'%>

app/views/buyers/pending_buyer_approval.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5"><%= @buyer.name%> - Clarification Approval</h2>
      </div>
      <div class="col text-right">
        <%= link_to 'Back', pending_buyer_approval_path, class: 'btn btn-black btn-sm' %>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'pending_buyer_approval'%>
  </div>
</div>

app/views/buyers/pending_buyer_comments.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5"><%= @buyer.name%> - Pending Item Comments</h2>
      </div>
      <div class="col text-right">
        <%= link_to 'Back', pending_buyer_comments_path, class: 'btn btn-black btn-sm' %>
      </div>
    </div>
  </div>
  <div id="couriers_table" class="mt-10">
    <%= render partial: 'pending_buyer_comments'%>
  </div>
</div>

app/views/buyers/show.html.erb
<div class="container-fluid mt-10 card shadow-sm" style="background-color: white;">
	<div class="card-header">
    <div class="row align-items-center">
      <div class="col">
        <h2 class="h5">Vendor - <%= @buyer.name %></h2>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col">
        <h6>Company - <%= @buyer.company %></h6>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col">
        <h6>Address - <%= @buyer.address %></h6>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col">
        <%= link_to 'Add Team', new_buyer_team_path(@buyer), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-black btn-sm'} %>
        <% if @buyer.teams.present? %>
	        <%= link_to 'Couriers', buyer_couriers_path(@buyer), class: 'btn btn-black btn-sm' %>
        <% end %>
      </div>
    </div>
  </div>
	<div id="teams_table">
	  <%= render partial: 'teams/index'%>
	</div>
</div>

<%= render partial: 'layouts/modal'%>

app/views/buyers/update.js.erb
<%= render partial: 'layouts/error.js.erb', locals: {item: @buyer}%>